### ISSUE TITLE
Maybe don't test-drive ToString()?

### ISSUE THREAD

**Issue by jbrains** [angellaa/Fraction#3]
If I use ToString() purely for debugging purposes, then I probably would not test-drive it. It seems Too Simple to Break and the cost of failure is too low to justify the investment.

HOWEVER, if I'm learning to write tests, such as in an unfamiliar language or with unfamiliar tools, then I would happily invest the time and effort in practising writing tests. I would encourage Novices practising TDD to write these tests.

**Comment by angellaa** [comment]
I agree with you, unless ToString is an actual requirement and used in some kind of UI for display purposes (that was an artificial requirement I implicitly added to the exercise). Interestingly, adding the test NegativeFraction in ToString helped me to discover a bug (I was printing "3/-8" instead of "-3/8"). Surprisingly all the other tests were passing but my logic of setting the sign of numerator and denominator was not correct (see the last commit https://github.com/angellaa/Fraction/commit/aae76a3f3db55909244bcfb9239e3347d4899cbf). The lesson learnt is that I haven't understood gcd sign deep enough, some additional tests on gcd would have helped (I was trusting the fact that the algorithm was well known and probably already well tested.... but any usage is different so it was a mistake). Anyway, as I already added the ToString tests I am going to keep them and close this issue.

**Comment by jbrains** [comment]
Indeed. Sometimes an integrated tests helps us find something, even though I typically don't want to depend on them for that. In this case, by luck, it helped you. 

I never use ToString for "real behavior", but I probably can't entirely justify that choice. I think it's arbitrary and has certain advantages and disadvantages.
